services:
  backend:
    environment:
      FLASK_ENV: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:ro
      - ./backend/wsgi.py:/app/wsgi.py:ro
    command:
      [
        "gunicorn",
        "--bind", "0.0.0.0:8000",
        "--workers", "1",
        "--threads", "2",
        "--reload",
        "--timeout", "300",
        "wsgi:app",
      ]
